name: Generate and Compile C# Code

on:
  release:
    types:
      - created

jobs:
  generate_and_compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate C# Code
        run: |
          # Add commands to generate your C# code
          # For example, you can use a code generation tool like T4 templates or any other method to generate code

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with your desired .NET version

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Specify the tag for the release
          release_name: Release v1.0.0  # Specify the name for the release
          draft: false
          prerelease: false

      - name: Upload compiled binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish  # Path to the compiled binaries or publish directory
          asset_name: compiled_binaries.zip  # Name for the uploaded asset
          asset_content_type: application/zip  # Content type of the asset
